apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  namespace: promethues-poc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-app
          image: rafay7655/flaskapp:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000